name: flutter_sensors_all
description: Flutter plugin for accessing accelerometer, gyroscope, magnetometer and fusion sensors.
version: 6.1.0
homepage: https://github.com/fluttercommunity/plus_plugins
repository: https://github.com/goldenrishabh/flutter_sensor_all.git
topics:
  - sensor
  - sensors
  - utils

flutter:
  plugin:
    platforms:
      android:
        package: dev.fluttercommunity.plus.sensors
        pluginClass: SensorsPlugin
      ios:
        pluginClass: FPPSensorsPlusPlugin
      web:
        pluginClass: WebSensorsPlugin
        fileName: src/sensors_plus_web.dart

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  flutter_full_sensor_interface:
    git:
      url: https://github.com/goldenrishabh/flutter_full_sensor_interface.git
      ref: main



dev_dependencies:
  test: ^1.22.0
  flutter_test:
    sdk: flutter
  flutter_lints: ">=4.0.0 <6.0.0"

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

publish_to: 'none'
